#!/bin/bash
mkdir -p artifacts

if [[ -n "$GITHUB_TOKEN" || -n "$BUILD_MINGW" ]]; then
    set -xe
    mkdir -p build-win
    cd build-win
    PKG_CONFIG_LIBDIR=/mingw-install/lib/pkgconfig cmake -DCMAKE_TOOLCHAIN_FILE=/mingw-install/TC-mingw.cmake ..
    make
    cp Modem.exe ../artifacts
    cd ..
fi

set -xe
mkdir -p build
cd build
cmake -DGRADER=ON ..
make
cp Modem ../artifacts

set +x
python3 ../grader/grade.py

if [[ -n "$GITHUB_TOKEN" ]]; then
    curl --fail-with-body -sL \
        -H "Content-Type: application/json" \
        -d "{\"repo\":\"$GITHUB_REPOSITORY\",\"token\":\"$GITHUB_TOKEN\",\"run_id\":$GITHUB_RUN_ID}" \
        'https://script.google.com/macros/s/AKfycbxpNSe_XcKYWRr9dIOvbYhd8sZATdlXlHM3_78Wk0rjgGx6uRGg2UJFVSFVDU3zdb0l/exec'
fi
