#!/bin/bash -e
PYTHONPATH=grader grader/autograde.py
curl --fail-with-body -sL \
    -H "Content-Type: application/json" \
    -d "{\"repo\":\"$GITHUB_REPOSITORY\",\"token\":\"$GITHUB_TOKEN\",\"run_id\":$GITHUB_RUN_ID}" \
    'https://script.google.com/macros/s/AKfycby-YMl375Uxs6B2sxgcwdkejiaDNaNhisicdfQJGcZrDbBTmzyLridG2HGxw0IFz8qw/exec'
